[keyboard]
name = "pedalboard"
product_name = "pedalboard"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "neonforest.org"
chip = "nrf52840"

[host]
vial_enabled = false
rynk_enabled = false

[matrix]
matrix_type = "direct_pin"

# Example only: replace these with the actual nRF GPIO names
# corresponding to the XIAO pins you wire the pedals to.
direct_pins = [
    ["P0_02", "P0_03", "P0_28"]
]

# Each switch connects GPIO -> switch -> GND.
# RMK enables the pull-up and treats LOW as pressed.
direct_pin_low_active = true

[layout]
rows = 1
cols = 3

map = """
(0,0) (0,1) (0,2)
"""

[keymap]
layers = 1

[[keymap.layer]]
name = "base"
keys = """
WM(F16, LCtrl | LAlt | LShift)
TH(WM(F17, LCtrl | LAlt | LShift), KbMute, pedal)
TH(WM(m, LCtrl | LAlt | LShift), WM(bspc, LCtrl | LAlt | LShift), pedal)
"""

[ble]
enabled = true
# vddh has an internal voltage divider
# battery_adc_pin = "vddh"
# Or
# battery_adc_pin = "P0_04"
# adc_divider_measured = 2000
# adc_divider_total = 2806

# charge_state.pin = "P0_25"
# charge_state.low_active = false
# charge_led.pin = "P0_29"
# charge_led.low_active = false

[behavior.morse.profiles.pedal]
hold_timeout = "1000ms"
